In [186]:
a = np.zeros((3,3,4))
# for ind, val in enumerate([4,5,6]):
#     a[:, ind, :] = val 
for i in [4,5,6]:
    a[:, 2, :] = i
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [6., 6., 6., 6.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [6., 6., 6., 6.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [6., 6., 6., 6.]]])

array([[4.67171428e-310],
       [0.00000000e+000],
       [2.41907520e-312],
       [2.14321575e-312]])

In [233]:
a = np.ndarray((4,4))[0]
a.reshape(4,1)
(np.repeat([a], 9))


array([4.67171428e-310, 4.67171428e-310, 4.67171428e-310, 4.67171428e-310,
       4.67171428e-310, 4.67171428e-310, 4.67171428e-310, 4.67171428e-310,
       4.67171428e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 2.41907520e-312, 2.41907520e-312,
       2.41907520e-312, 2.41907520e-312, 2.41907520e-312, 2.41907520e-312,
       2.41907520e-312, 2.41907520e-312, 2.41907520e-312, 2.14321575e-312,
       2.14321575e-312, 2.14321575e-312, 2.14321575e-312, 2.14321575e-312,
       2.14321575e-312, 2.14321575e-312, 2.14321575e-312, 2.14321575e-312])

In [33]:
import numpy as np

prob = np.zeros((4,4))
prob[0][0] = 5/6
prob[0][1] = 1/6
prob[1][1] = 1/6
prob[1][2] = 4/6
prob[1][3] = 1/6
prob[2][2] = 3/4
prob[2][3] = 1/4
prob[3][0] = 1
print(prob)
print()
#should reward be a matrix?
# rew = np.zeros((4,4))
# rew[0][0] = 70
# rew[0][1] = 70
# rew[1][1] = 50
# rew[1][2] = 50
# rew[1][3] = 50
# rew[2][2] = -20
# rew[2][3] = -20
# rew[3][0] = -100
rew = np.zeros((4,1))
rew[0] = 70
rew[1] = 50
rew[2] = -2
rew[3] = -100
print(rew)

[[0.83333333 0.16666667 0.         0.        ]
 [0.         0.16666667 0.66666667 0.16666667]
 [0.         0.         0.75       0.25      ]
 [1.         0.         0.         0.        ]]

[[  70.]
 [  50.]
 [  -2.]
 [-100.]]


In [35]:
gamma = 0.6
A = np.linalg.inv(np.eye(4) - gamma * prob)
val = np.linalg.inv(np.eye(4) - gamma * prob) @ rew
val

array([[150.33250208],
       [ 51.66251039],
       [ -6.30922693],
       [ -9.80049875]])

In [68]:
rew = np.ones((16,1))*(-1)
rew[0] = 0
rew[-1] = 0

prob = np.zeros((16,16))
prob[0][0] = 1
prob[1][1] = 1/4
prob[1][0] = 1/4
prob[1][2] = 1/4
prob[1][5] = 1/4
prob[2][2] = 1/4
prob[2][1] = 1/4
prob[2][3] = 1/4
prob[2][6] = 1/4
prob[3][3] = 2/4
prob[3][2] = 1/4
prob[3][7] = 1/4
prob[4][4] = 1/4
prob[4][0] = 1/4
prob[4][5] = 1/4
prob[4][8] = 1/4
prob[5][1] = 1/4
prob[5][6] = 1/4
prob[5][9] = 1/4
prob[5][4] = 1/4
prob[6][5] = 1/4
prob[6][2] = 1/4
prob[6][7] = 1/4
prob[6][10] = 1/4
prob[7][3] = 1/4
prob[7][7] = 1/4
prob[7][11] = 1/4
prob[7][6] = 1/4
prob[8][4] = 1/4
prob[8][9] = 1/4
prob[8][12] = 1/4
prob[8][8] = 1/4
prob[9][5] = 1/4
prob[9][10] =1/4 
prob[9][13] =1/4 
prob[9][8] = 1/4
prob[10][6] = 1/4
prob[10][11] =1/4 
prob[10][14] =1/4 
prob[10][9] = 1/4
prob[11][7] = 1/4
prob[11][11] =1/4 
prob[11][15] =1/4 
prob[11][10] =1/4 
prob[12][8] = 1/4
prob[12][13] = 1/4
prob[12][12] = 2/4 
prob[13][9] =1/4
prob[13][14] = 1/4
prob[13][13] = 1/4
prob[13][12] = 1/4
prob[14][10] = 1/4 
prob[14][15] = 1/4
prob[14][14] = 1/4
prob[14][13] = 1/4
prob[15][15] = 1

print(rew)
print(prob)



[[ 0.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]]
[[1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.25 0.25 0.25 0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.   0.25 0.25 0.25 0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.   0.   0.25 0.5  0.   0.   0.   0.25 0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.25 0.   0.   0.   0.25 0.25 0.   0.   0.25 0.   0.   0.   0.   0.
  0.   0.  ]
 [0.   0.25 0.   0.   0.25 0.   0.25 0.   0.   0.25 0.   0.   0.   0.
  0.   0.  ]
 [0.   0.   0.25 0.   0.   0.25 0.   0.25 0.   0.   0.25 0.   0.   0.
  0.   0.  ]
 [0.   0.   0.   0.25 0.   0.   0.25 0.25 0.   0.   0.   0.25 0.   0.
  0.   0.  ]
 [0.   0.   0.   0.   0.25 0.   0.   0.   0.25 0.25 0.   0.   0.25 0.
  0.   0.  ]
 [0.   0.   0.   0.   0.   0.25 0.   0.   0.25 0.   0.25 0.   0.   0.25
  0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.25 0. 

In [69]:
gamma = 0.6
val = np.round(np.linalg.inv(np.eye(16) - gamma * prob) @ rew, 1)
for ind, i in enumerate(val):
    print('s{}, '.format(ind), i[0])

s0,  0.0
s1,  -2.0
s2,  -2.4
s3,  -2.5
s4,  -2.0
s5,  -2.3
s6,  -2.4
s7,  -2.4
s8,  -2.4
s9,  -2.4
s10,  -2.3
s11,  -2.0
s12,  -2.5
s13,  -2.4
s14,  -2.0
s15,  0.0


In [70]:
#why doesnt this match with the textbook example?
#ANALYTICALY OPTIMAL VALUES
val.reshape((4,4))

array([[ 0. , -2. , -2.4, -2.5],
       [-2. , -2.3, -2.4, -2.4],
       [-2.4, -2.4, -2.3, -2. ],
       [-2.5, -2.4, -2. ,  0. ]])

In [93]:
#EXAMPLES STAIRS
p = np.zeros((7,7))
p[0][0] = 1
p[6][6] = 1
ind = 0
for i in range(1,6):
    p[i][ind] = 1/2
    p[i][ind+2] = 1/2
    ind += 1
print("transition probability | equiprobable policy")
print(p)

r = np.zeros((7,7))
ind = 0
for i in range(1,6):
    r[i][ind] = 1
    r[i][ind+2] = -1
    ind += 1
r[1][0] = -10
r[6][6] = 10
print('reward | equiprobable policy')
print(r)

transition probability | equiprobable policy
[[1.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.  0.  0.  1. ]]
reward | equiprobable policy
[[  0.   0.   0.   0.   0.   0.   0.]
 [-10.   0.  -1.   0.   0.   0.   0.]
 [  0.   1.   0.  -1.   0.   0.   0.]
 [  0.   0.   1.   0.  -1.   0.   0.]
 [  0.   0.   0.   1.   0.  -1.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.]
 [  0.   0.   0.   0.   0.   0.  10.]]


In [175]:
#policy evaluation
class Stairs:

    def __init__(self, gamma):
        self.gamma = gamma

    def policyEvaluation(self):
        '''compute equiprobable policy'''

        def policy(action: int, state: int) -> float:
            prob = 1/2
            assert 0 < prob < 1, "probability must be in range [0,1]"
            return prob

        def reward(action, state):
            next_state = state + action
            if next_state == 6:
                return 10
            elif next_state == 0:
                return -10
            else:
                return -action
            
        def iterativeInPlaceBellman(V: np.ndarray, curr_state: int,
                            gamma: float) -> float:
            new_val = 0
            for action in [-1, 1]: #only two actions
                pi = policy(action, curr_state)
                r = reward(action, curr_state)
                vn = V[curr_state + action]
                new_val +=  pi * (r + gamma * vn)
            return new_val

        theta = 0.001 #change treshold to stop iteration
        n_states = 7
        V = np.zeros((n_states)) #initial empty array of values at states
        max_it = 50 #iteration treshold  
        it = 0 
        while it < max_it:
            dlt = 0 #change between two consequtive states
            for curr_state in range(1, n_states-1):
                v = V[curr_state]
                V[curr_state] = iterativeInPlaceBellman(V, curr_state, self.gamma) #try to impelement with two vectors
                dlt = max(dlt, abs(v - V[curr_state])) #always save maximal change of values
            it += 1
            print('{} iteration'.format(it))
            print(np.round(V,2))
            if dlt < theta:
                break
            self.V = V
        #optional
        # return V



    def policyImprovement(self) -> np.ndarray:
        '''0 - go left, 1 - go right'''
        V = self.V
        out = np.zeros(7)
        for i in range(1, len(V)-1):
            if V[i-1] > V[i+1]:
                out[i] = 0
            elif V[i-1] < V[i+1]:
                out[i] = 1
            else:
                out[i] = random_choice = np.random.choice([0, 1])
        print(out)
        # return out

    def analyticalSolution(self):
        p = np.zeros((7,7))
        p[0][0] = 1
        p[6][6] = 1
        ind = 0
        for i in range(1,6):
            p[i][ind] = 1/2
            p[i][ind+2] = 1/2
            ind += 1
        print("transition probability | equiprobable policy")
        print(p)

        r = np.zeros((7,7))
        ind = 0
        for i in range(1,6):
            r[i][ind] = 1
            r[i][ind+2] = -1
            ind += 1
        r[1][0] = -10
        r[6][6] = 10
        print('reward | equiprobable policy')
        print(r)
        val = np.round(np.linalg.inv(np.eye(7) - gamma * p) @ r, 1)
        print('value state matrix??? \n', val)
        # return val

#TO DO: policy improvement
a = Stairs(gamma)
a.policyEvaluation()

1 iteration
[ 0.   -5.5  -2.48 -1.11 -0.5   5.27  0.  ]
2 iteration
[ 0.   -6.61 -3.48 -1.79  1.57  6.21  0.  ]
3 iteration
[ 0.   -7.06 -3.98 -1.09  2.3   6.54  0.  ]
4 iteration
[ 0.   -7.29 -3.77 -0.66  2.64  6.69  0.  ]
5 iteration
[ 0.   -7.2  -3.54 -0.4   2.83  6.77  0.  ]
6 iteration
[ 0.   -7.09 -3.37 -0.24  2.94  6.82  0.  ]
7 iteration
[ 0.   -7.02 -3.27 -0.15  3.    6.85  0.  ]
8 iteration
[ 0.   -6.97 -3.2  -0.09  3.04  6.87  0.  ]
9 iteration
[ 0.   -6.94 -3.16 -0.05  3.07  6.88  0.  ]
10 iteration
[ 0.   -6.92 -3.14 -0.03  3.08  6.89  0.  ]
11 iteration
[ 0.   -6.91 -3.13 -0.02  3.09  6.89  0.  ]
12 iteration
[ 0.   -6.91 -3.12 -0.01  3.1   6.89  0.  ]
13 iteration
[ 0.   -6.9  -3.11 -0.01  3.1   6.89  0.  ]
14 iteration
[ 0.   -6.9  -3.11 -0.    3.1   6.9   0.  ]
15 iteration
[ 0.   -6.9  -3.11 -0.    3.1   6.9   0.  ]
16 iteration
[ 0.   -6.9  -3.11 -0.    3.1   6.9   0.  ]
17 iteration
[ 0.  -6.9 -3.1 -0.   3.1  6.9  0. ]


In [174]:
a.policyImprovement()


ValueError: could not convert string to float: 'left'

In [172]:
a.analyticalSolution()

transition probability | equiprobable policy
[[1.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.  0.  0.  1. ]]
reward | equiprobable policy
[[  0.   0.   0.   0.   0.   0.   0.]
 [-10.   0.  -1.   0.   0.   0.   0.]
 [  0.   1.   0.  -1.   0.   0.   0.]
 [  0.   0.   1.   0.  -1.   0.   0.]
 [  0.   0.   0.   1.   0.  -1.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.]
 [  0.   0.   0.   0.   0.   0.  10.]]
value state matrix??? 
 [[  0.   -0.    0.    0.   -0.   -0.   -0. ]
 [-13.8   0.9  -0.9  -0.6  -0.4  -0.3   5.8]
 [ -8.6   1.9   0.3  -1.3  -0.9  -0.6  12.8]
 [ -5.2   1.1   1.5   0.   -1.5  -1.1  22.7]
 [ -2.9   0.6   0.9   1.3  -0.3  -1.9  37.6]
 [ -1.3   0.3   0.4   0.6   0.9  -0.9  60.9]
 [  0.    0.    0.    0.    0.    0.  100. ]]
